### ISSUE TITLE
Prep February 2024 release

### ISSUE THREAD

**Issue by willingc** [pyOpenSci/pyosMeta#102]
Let's begin releasing this package at the end of each month. 

## February 2024 Release Prep Checklist
- [x] Create milestone for release
- [x] Assign issues to the milestone
- [x] Test release
- [x] Update CHANGELOG.md and create a new unreleased section: @willingc
- [x] Release to PyPI (for now manually; optimistically automated using hatch)
- [x] Test PyPI release installation
- [x] Release 0.2.3 to PyPI: @lwasser
- [x] #118
- [x] Close Feb 2024 milestone: @willingc
- [x] Open March 2024 milestone with a due date 2024-03-31: @willingc

**Comment by lwasser** [comment]
@willingc [test pypi has pyosmeta on it now too!](https://test.pypi.org/project/pyosmeta/) however hugo's post on test pypi being difficult as a test bed is accurate. essentially it will only install things on test pypi which means that many dependencies might be super dated and break things when you try to install the package from there. in our case [pydantic](https://test.pypi.org/project/pydantic/) is a version from 2020 (assuming it's the right pydantic). should we just remove the test pypi build component al together? or what do you think is best?

the good news is releases work. i do want to update our release file but that is a small thing that we could do in march if we want to test drive a release this week.

**Comment by willingc** [comment]
Awesome @lwasser. My recommendation would be to create a release this week. I'm happy to update the Changelog for release.

I think we can move away from test pypi. We can noodle over the best way to test release build without using testpypi. We should be using a recent version of pydantic. All of this can wait until March.

Let's call the February release 0.2.3. I will open a PR for changelog. After that lands, you can do a release to PyPI.

**Comment by lwasser** [comment]
Sounds good to me @willingc !!! 🙌✨️
