### ISSUE TITLE
Fix: README on PyPI displaying out of date version

### ISSUE THREAD

**Issue by willingc** [pyOpenSci/pyosMeta#117]
This is likely due to our automation and the order of operations. README tag says v0.2.2 for the v0.2.3 release.

<img width="1213" alt="Screenshot 2024-03-01 at 2 38 57 PM" src="https://github.com/pyOpenSci/pyosMeta/assets/2680980/8003d7d2-d55f-400e-bae3-86fe27d971f2">

**Comment by lwasser** [comment]
perhaps badges take a bit of time to sync up? 🤷‍♀️ we could watch that next time.

**Comment by willingc** [comment]
Thanks for checking. I'm guessing its caching or propagation time on PyPI. I'm going to close.
