### ISSUE TITLE
Broken build - yet again

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/pyosMeta#168]
This package is used to update our contributor info on the website. Right now the build is broken - again.

Please [see here](https://github.com/pyOpenSci/pyopensci.github.io/actions/workflows/update-contribs-reviews.yml).

@blink1073 if you happen to be looking for another CI issue to fix this one might include some python. i'm also happy to give you merge permissions if that is of interest!! this build seems to fail periodically. most often it's because someone adds something to our review template that i hadn't expected when parsing the issues! But it's important as it keeps our website [packages](https://www.pyopensci.org/python-packages.html) listing & [contributor](https://www.pyopensci.org/our-community/index.html#pyopensci-community-contributors) list up to date.

**Comment by lwasser** [comment]
a new release might fix this issue.

**Comment by blink1073** [comment]
Yes, it looks like it needs #166

**Comment by blink1073** [comment]
I'm happy to accept write permissions, and also look for a way to test this workflow as part of PRs.

**Comment by blink1073** [comment]
PR: https://github.com/pyOpenSci/pyosMeta/pull/170

**Comment by lwasser** [comment]
sweet. i just made you a maintainer of this repo and added you to our org. i can add you to others as needed too! please just let me know what permissions you need where!

**Comment by blink1073** [comment]
will do, thanks!

**Comment by lwasser** [comment]
And now that ci build is helping me troubleshoot here before the website build breaks. thank you @blink1073 there is one more bug to resolve but i'll do that in a separate issue and will close this one!!
