### ISSUE TITLE
Support new review template format - process both reviewers list and eic

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/pyosMeta#173]
from @pllim 

"About that error, looks like https://github.com/pyOpenSci/software-submission/issues/152 (automata) has format of "Reviewers: X, Y, Z" but other issues have "Reviewer 1: X" followed by "Reviewer 2: Y"" 

We have made a few updates to our review template. 

1. instead of having reviewer 1: and reviewer 2 as separate entries - we have a reviewers field. this field accepts an array of github usernames. Right now the workflow is failing on automata as it uses the new template! We will want to add a check to see what reviewer format the field is provided with (reviewers vs reviewer x). Then we can process the names accordingly. This might require an alias on the pydantic end of things.
2. We also added the EiC field - make sure we support ingesting that field into our pydantic model & then the output yaml file. 

when this is addressed we can then close #77 as well.

**Comment by sneakers-the-rat** [comment]
my bad, i saw that the previous style was changed and i just followed the list format, i can do this rn

**Comment by lwasser** [comment]
@sneakers-the-rat we will need to update the  workflow to properly parse reviewers in both formats -- the legacy format 

we do want to support that format of `reviewers: @ reviewer1, @ reviewr2, etc` because that will allow us to more easily integrate the bot! But our pydantic model right now only supports reviewer_1 and reviewer_2. so i think we need a validator that parses both reviewer_x and reviewers fields. But also when it grabs the data i suspect we need to fix something there as well. 

<img width="893" alt="Screenshot 2024-07-02 at 6 47 49 PM" src="https://github.com/pyOpenSci/pyosMeta/assets/7649194/bbda0455-cf35-45d5-b822-aa24b3919273">

no apologies needed on your end!! i just made the template change a while ago and forgot i needed to open an issue and update things here. i'm going to merge #172 because that will fix the blank packages page issue!! 😆 which is a very special new "feature".

**Comment by sneakers-the-rat** [comment]
dw i'm refactoring the parser so this is eaasier (and ya handles the multiple formats and gives us room to grow)
