### ISSUE TITLE
Update .env-default file for configuring GitHub token

### ISSUE THREAD

**Issue by ehinman** [pyOpenSci/pyosMeta#195]
The .env-default file contains the text `API_TOKEN=`, and it should say `GITHUB_TOKEN=` to be used correctly.

**Comment by lwasser** [comment]
closing this as it was addressed in #196

**Comment by lwasser** [comment]
@ehinman it was really wonderful to meet you at scipy! thank you again for joining our sprint and for contributing to pyOpenSci!
