### ISSUE TITLE
Release v1.3.4 

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/pyosMeta#202]
Hi everyone! we need to create a new release of this package that will fix some issues with how the contributor data is parsed

https://github.com/pyOpenSci/pyopensci.github.io/pull/452/files#diff-c4bf8c3b089fbd17d00af382bbaa613a9e20c8d78363cf44785fa59047a96d77L426

notice now people are being moved to emeritus advisory roles by mistake because  of a bug i found and fixed here #200 
@willingc also fixed a test bug here: #199 that was causing pr's to fail. If anyone is open to generating a update change log with these contributions (plus the contributions from the pyopensci sprint at scipy 2024 that pr is welcome!!

then we can make a new release and fix our website build. 

so the steps needed

2. update the change log to represent the current changes made (we haven't kept it up to date). submit a pr and merge it
3. create a new release on github
4. that release will trigger a push to pypi! 
then we can rerun the contributor workflow.

**Comment by willingc** [comment]
@lwasser Let's troubleshoot: https://github.com/pyOpenSci/pyosMeta/pull/200#discussion_r1700502035 prior to release.

Contributors, please feel free to do the other release steps. :smile:

**Comment by lwasser** [comment]
ok i think @willingc please correct me if i'm wrong. we are now really ready for a new patch release? given #203 and the code cov change in #205

**Comment by willingc** [comment]
Go for it @lwasser. It was good to go before my CI change too (for future reference) :smile:

**Comment by lwasser** [comment]
thank you @willingc  ❤️ !! i also didn't know about the coverage settings. i am going to use that in stravalib as sometimes it complains if something is 1% off.

**Comment by willingc** [comment]
Closed by #206
