### ISSUE TITLE
Review settings for Codacy linting service

### ISSUE THREAD

**Issue by willingc** [pyOpenSci/pyosMeta#80]
The Codacy linter seems to be providing conflicting guidance on validity of Markdown style.

Let's review that it is checking correctly and that the style used matches our desired style.

**Comment by lwasser** [comment]
Sure thing. you know i used codacy a very long time ago and remember it being useful. BUT i also remember we added a config file to ensure it aligned  with our goals. we could either decide it's not the right tool for us OR that we want to turn off markdown linting (the things it flagged seem a bit odd).

**Comment by lwasser** [comment]
i found this [pre-commit hook](https://github.com/igorshubovych/markdownlint-cli) and tested it out locally. it looks for things like duplicate headers, line length and missing language notations on code brackets in addition to list spacing, etc. 

i'm not sure if it will make codacy happy or not but we could use a linter like this to enforce markdown syntax and tell codacy to ignore markdown as one option.

**Comment by willingc** [comment]
Since this seems to no longer be an issue, I'm closing this.
